<?php

return [
    [
        'slug' => 'medical_history',
        'name' => 'Medical History',
        'icon' => 'folder',
        'color' => '#3b82f6',
        'order' => 1,
        'is_visible' => true,
    ],
    [
        'slug' => 'pre_op',
        'name' => 'Pre Operation',
        'icon' => 'clipboard',
        'color' => '#f59e0b',
        'order' => 2,
        'is_visible' => true,
    ],
    [
        'slug' => 'operation_sheet',
        'name' => 'Operation',
        'icon' => 'scissors',
        'color' => '#8b5cf6',
        'order' => 3,
        'is_visible' => true,
    ],
    [
        'slug' => 'post_op',
        'name' => 'Post Operation',
        'icon' => 'heart',
        'color' => '#10b981',
        'order' => 4,
        'is_visible' => true,
    ],
    [
        'slug' => 'medications',
        'name' => 'Medications',
        'icon' => 'pill',
        'color' => '#ef4444',
        'order' => 5,
        'is_visible' => true,
    ],
    [
        'slug' => 'lab_results',
        'name' => 'Lab Results',
        'icon' => 'beaker',
        'color' => '#06b6d4',
        'order' => 6,
        'is_visible' => true,
    ],
    [
        'slug' => 'imaging',
        'name' => 'Imaging',
        'icon' => 'camera',
        'color' => '#ec4899',
        'order' => 7,
        'is_visible' => true,
    ],
    [
        'slug' => 'follow_up',
        'name' => 'Follow-up',
        'icon' => 'calendar',
        'color' => '#14b8a6',
        'order' => 8,
        'is_visible' => true,
    ],
    [
        'slug' => 'notes',
        'name' => 'Other Notes',
        'icon' => 'document',
        'color' => '#6b7280',
        'order' => 9,
        'is_visible' => true,
    ],
];
